package com.uims.backend.service;

import com.uims.backend.model.*;
import com.uims.backend.repository.DepartmentRepository;
import com.uims.backend.repository.ProjectRepository;
import com.uims.backend.repository.RoadRepository;
import com.uims.backend.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class ProjectService {

    private static final Logger log = LoggerFactory.getLogger(ProjectService.class);

    /** Number of days after COMPLETED status that restoration must be verified. */
    private static final int SLA_WINDOW_DAYS = 14;

    @Autowired
    private ProjectRepository projectRepository;

    @Autowired
    private RoadRepository roadRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private DepartmentRepository departmentRepository;

    @Autowired
    private ImpactAnalysisService impactAnalysisService;

    // ────────────────────────────────────────────────────────────────────
    // Public API methods
    // ────────────────────────────────────────────────────────────────────

    public ImpactReport analyzeProject(ProjectRequest request) {
        Road road = roadRepository.findById(request.getRoadId())
                .orElseThrow(() -> new RuntimeException("Road not found"));

        List<String> conflicts = detectConflicts(request);
        return impactAnalysisService.analyzeImpact(request, road, conflicts);
    }

    public Project createProject(ProjectRequest request, String email) {
        User official = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));

        if (official.getRole() != Role.ROLE_DEPARTMENT || official.getDepartment() == null) {
            throw new RuntimeException("User does not have a department assigned");
        }

        Road road = roadRepository.findById(request.getRoadId())
                .orElseThrow(() -> new RuntimeException("Road not found"));

        ImpactReport report = analyzeProject(request);

        Project project = new Project();
        project.setTitle(request.getTitle());
        project.setDescription(request.getDescription());
        project.setWorkType(request.getWorkType());
        project.setRoad(road);
        project.setDepartment(official.getDepartment());
        project.setStartDate(request.getStartDate());
        project.setEndDate(request.getEndDate());
        project.setLaneClosurePercentage(request.getLaneClosurePercentage());
        project.setImpactScore(report.getImpactScore());
        project.setImpactRecommendation(report.getRecommendation());

        if (request.getRecommendedStartTime() != null) {
            project.setRecommendedStartTime(LocalDateTime.parse(request.getRecommendedStartTime().replace(" ", "T")));
        }
        if (request.getRecommendedEndTime() != null) {
            project.setRecommendedEndTime(LocalDateTime.parse(request.getRecommendedEndTime().replace(" ", "T")));
        }
        project.setDisruptionScoreAtApproval(request.getDisruptionScoreAtApproval());

        // Persist the plain-English approval receipt generated by ImpactAnalysisService
        project.setApprovalReceipt(report.getApprovalReceipt());

        // SLA: initialise breach flag (deadline is only set when COMPLETED)
        project.setSlaBreached(false);

        // Status: CRITICAL impact requires manual admin review before activation
        project.setStatus(report.getSeverity().equals("CRITICAL") ? "PENDING_APPROVAL" : "APPROVED");

        return projectRepository.save(project);
    }

    /**
     * Transitions a project to a new status.
     *
     * <p>When the target status is {@code "COMPLETED"}, the 14-day restoration
     * SLA countdown is started by setting {@code restorationDeadline}.
     *
     * @param id        project primary key
     * @param newStatus target status string (e.g., "COMPLETED", "REJECTED", "IN_PROGRESS")
     * @param email     authenticated user's email (used for ownership check)
     * @return the saved, updated Project entity
     * @throws RuntimeException if the project is not found or the user lacks permission
     */
    @Transactional
    public Project updateProjectStatus(Long id, String newStatus, String email) {
        Project project = projectRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Project not found: " + id));

        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found: " + email));

        // Department officials can only update their own department's projects;
        // admin users may update any project.
        if (user.getRole() == Role.ROLE_DEPARTMENT) {
            if (project.getDepartment() == null ||
                    !project.getDepartment().getId().equals(user.getDepartment().getId())) {
                throw new RuntimeException("You are not authorised to update this project.");
            }
        }

        project.setStatus(newStatus);

        // ── SLA Countdown ──────────────────────────────────────────────
        if ("COMPLETED".equalsIgnoreCase(newStatus)) {
            LocalDateTime deadline = LocalDateTime.now().plusDays(SLA_WINDOW_DAYS);
            project.setRestorationDeadline(deadline);
            log.info("Project [{}] marked COMPLETED. Restoration SLA deadline set to {}.",
                    project.getId(), deadline);
        }

        return projectRepository.save(project);
    }

    // ────────────────────────────────────────────────────────────────────
    // Conflict detection (shared by analyzeProject and createProject)
    // ────────────────────────────────────────────────────────────────────

    private List<String> detectConflicts(ProjectRequest request) {
        return detectConflicts(request.getRoadId(), request.getStartDate(), request.getEndDate(), request.getWorkType());
    }

    public List<String> detectConflicts(Long roadId, java.time.LocalDate startDate, java.time.LocalDate endDate, String workType) {
        List<String> conflicts = new ArrayList<>();
        List<Project> existingProjects = projectRepository.findByRoadId(roadId);

        for (Project p : existingProjects) {
            // Check spatio-temporal overlap (naive check for overlapping dates on the same road)
            boolean dateOverlap = !(endDate.isBefore(p.getStartDate()) || startDate.isAfter(p.getEndDate()));

            if (dateOverlap && !p.getStatus().equals("COMPLETED") && !p.getStatus().equals("REJECTED")) {
                conflicts.add(p.getDepartment().getName() + " already has '" + p.getTitle() + "' planned during this time.");
            }

            // Check recent resurfacing rule
            if ("Resurfacing".equalsIgnoreCase(p.getWorkType()) && p.getStatus().equals("COMPLETED")) {
                // If it was completed within the last 6 months, and new work is excavation
                if (p.getEndDate().plusMonths(6).isAfter(startDate) && (workType != null && workType.contains("Excavation"))) {
                    conflicts.add("Road was recently resurfaced on " + p.getEndDate() + ". Excavation is restricted for 6 months unless emergency.");
                }
            }
        }
        return conflicts;
    }

    public List<Project> getDepartmentProjects(Long departmentId) {
        return projectRepository.findByDepartmentId(departmentId);
    }

    // ────────────────────────────────────────────────────────────────────
    // SLA Watchdog — runs daily at 02:00
    // ────────────────────────────────────────────────────────────────────

    /**
     * Nightly scheduled job that scans for COMPLETED projects whose
     * restoration SLA deadline has passed without sign-off.
     *
     * <p>For each breached project:
     * <ol>
     *   <li>Sets {@code sla_breached = true}.</li>
     *   <li>Escalates the project status to {@code "SLA_BREACHED"}.</li>
     *   <li>Recomputes the owning department's {@code avg_restoration_delay_days}
     *       as the mean overdue days across all its SLA-breached projects.</li>
     *   <li>Increments the department's {@code total_conflicts_caused} by the
     *       number of unresolved conflicts involving this project.</li>
     * </ol>
     *
     * <p>The cron expression {@code "0 0 2 * * *"} fires at 02:00:00 every day.
     */
    @Scheduled(cron = "0 0 2 * * *")
    @Transactional
    public void runSlaWatchdog() {
        LocalDateTime now = LocalDateTime.now();
        log.info("SLA Watchdog starting at {}.", now);

        // ── 1. Find all projects whose SLA has expired ─────────────────
        List<Project> breachedProjects = projectRepository
                .findByStatusAndSlaBreachedFalseAndRestorationDeadlineBefore("COMPLETED", now);

        if (breachedProjects.isEmpty()) {
            log.info("SLA Watchdog: no breaches detected.");
            return;
        }

        log.warn("SLA Watchdog: {} breach(es) detected.", breachedProjects.size());

        // ── 2. Flag each breached project ───────────────────────────────
        for (Project project : breachedProjects) {
            project.setSlaBreached(true);
            project.setStatus("SLA_BREACHED");
            projectRepository.save(project);

            log.warn("Project [{}] '{}' (dept: {}) has breached SLA. Deadline was {}.",
                    project.getId(),
                    project.getTitle(),
                    project.getDepartment() != null ? project.getDepartment().getName() : "N/A",
                    project.getRestorationDeadline());
        }

        // ── 3. Update department scorecards ─────────────────────────────
        // Group breached projects by department to minimise DB writes
        Map<Long, List<Project>> byDepartment = breachedProjects.stream()
                .filter(p -> p.getDepartment() != null)
                .collect(Collectors.groupingBy(p -> p.getDepartment().getId()));

        byDepartment.forEach((deptId, projects) -> {
            Department dept = departmentRepository.findById(deptId).orElse(null);
            if (dept == null) return;

            // Recompute rolling average across ALL breached projects for this dept
            List<Project> allBreached = projectRepository.findByDepartmentIdAndSlaBreachedTrue(deptId);

            double avgDelayDays = allBreached.stream()
                    .filter(p -> p.getRestorationDeadline() != null)
                    .mapToLong(p -> ChronoUnit.DAYS.between(p.getRestorationDeadline(), now))
                    // A negative value would mean the deadline hasn't passed yet — clamp to 0
                    .filter(days -> days > 0)
                    .average()
                    .orElse(0.0);

            dept.setAvgRestorationDelayDays(avgDelayDays);

            // Increment conflict counter by the number of newly breached projects
            // (each breached project is treated as having caused one conflict event)
            dept.setTotalConflictsCaused(dept.getTotalConflictsCaused() + projects.size());

            departmentRepository.save(dept);

            log.info("Department '{}' scorecard updated — avgDelay: {} days, totalConflicts: {}.",
                    dept.getName(), avgDelayDays, dept.getTotalConflictsCaused());
        });

        log.info("SLA Watchdog completed.");
    }
}

